#!/usr/bin/env bash
# UxPlay AirPlay2 receiver → Annex-B H.264 FIFO (pre-decode tap via -vrtp).
# Idle black H.264 is generated by inject_h264.py when no AirPlay client is active.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck disable=SC1091
if [[ -f /etc/airplay-aa/bridge.env ]]; then source /etc/airplay-aa/bridge.env; else source "${ROOT}/config/bridge.env"; fi

mkdir -p "$(dirname "$AIRPLAY_AA_H264")" "$AIRPLAY_AA_LOGDIR"
rm -f "$AIRPLAY_AA_H264"
mkfifo "$AIRPLAY_AA_H264"

cleanup() {
  jobs -p | xargs -r kill 2>/dev/null || true
}
trap cleanup EXIT INT TERM

# Scale/transcode AirPlay H.264 (any mirror size) to AA baseline 800x480@30.
# UxPlay inserts rtph264pay before this fragment when -vrtp is used.
VRTP_TAIL="pt=96 ! application/x-rtp,media=video,encoding-name=H264 ! rtph264depay ! h264parse ! avdec_h264 ! videoconvert ! videoscale ! videorate ! video/x-raw,format=I420,width=${AIRPLAY_AA_WIDTH},height=${AIRPLAY_AA_HEIGHT},framerate=${AIRPLAY_AA_FPS}/1 ! x264enc tune=zerolatency speed-preset=ultrafast key-int-max=${AIRPLAY_AA_FPS} bframes=0 byte-stream=true ! video/x-h264,stream-format=byte-stream,alignment=au,profile=baseline ! h264parse config-interval=-1 ! filesink location=${AIRPLAY_AA_H264} sync=false"

echo "starting UxPlay as '${AIRPLAY_AA_NAME}' (AirPlay receiver, no local display)"
exec uxplay \
  -n "${AIRPLAY_AA_NAME}" \
  -nh \
  -vsync no \
  -as 0 \
  -vs 0 \
  -vrtp "${VRTP_TAIL}" \
  >>"$AIRPLAY_AA_LOGDIR/uxplay.log" 2>&1
